name: Install telnyx Compromised Package

on:
  workflow_dispatch:
    inputs:
      telnyx_version:
        description: "Telnyx package version to install"
        required: true
        type: choice
        options:
          - "both"
          - "4.87.1"
          - "4.87.2"
        default: "both"

permissions: read-all

jobs:
  install-telnyx-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install telnyx 4.87.1 from local tar.gz
        if: inputs.telnyx_version == '4.87.1' || inputs.telnyx_version == 'both'
        continue-on-error: true
        run: |
          pip install ./telnyx-4.87.1.tar.gz

      - name: Install telnyx 4.87.2 from local tar.gz
        if: inputs.telnyx_version == '4.87.2' || inputs.telnyx_version == 'both'
        continue-on-error: true
        run: |
          pip install ./telnyx-4.87.2.tar.gz

      - name: Create sample telnyx client
        continue-on-error: true
        run: |
          python3 << 'EOF'
          import telnyx
          print("telnyx version:", telnyx.__version__)

      - name: Print artifacts
        run: |
          ls /tmp

  install-telnyx-windows:
    runs-on: windows-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install telnyx 4.87.1 from local tar.gz
        if: inputs.telnyx_version == '4.87.1' || inputs.telnyx_version == 'both'
        continue-on-error: true
        run: |
          pip install ./telnyx-4.87.1.tar.gz

      - name: Install telnyx 4.87.2 from local tar.gz
        if: inputs.telnyx_version == '4.87.2' || inputs.telnyx_version == 'both'
        continue-on-error: true
        run: |
          pip install ./telnyx-4.87.2.tar.gz

      - name: Create sample telnyx client
        continue-on-error: true
        run: |
          python3 << 'EOF'
          import telnyx
          print("telnyx version:", telnyx.__version__)

        shell: bash

      - name: Print artifacts
        run: |
          dir %TEMP%
        shell: cmd
